import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js";
import { getFirestore, collection, getDocs, getDoc, addDoc, updateDoc, deleteDoc, doc, query, limit, where, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyBXE2N125GMbL9nKPOgsKfc2FLJ1HsBmyU",authDomain:"school-house-57188.firebaseapp.com",projectId:"school-house-57188",storageBucket:"school-house-57188.firebasestorage.app",messagingSenderId:"117100890866",appId:"1:117100890866:web:4d13836bdbe6b348ef9e6b",measurementId:"G-DFJSM8B884"};
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp);
const root=document.getElementById('app'),toast=document.getElementById('toast');
let currentUser=null,currentProfile=null,currentView='dashboard',firestoreReady=true,lastRows={};
const NAV=[['dashboard','Αρχική'],['students','Μαθητές'],['absences','Απουσίες'],['tuition','Δίδακτρα'],['payments','Πληρωμές']];
const views={dashboard:{title:'Αρχική',body:dashboardHtml},students:{title:'Μαθητές',body:studentsHtml},absences:{title:'Απουσίες',body:absencesHtml},tuition:{title:'Δίδακτρα',body:tuitionHtml},payments:{title:'Πληρωμές',body:paymentsHtml}};
const COLLECTIONS={student:'students',absence:'absences',tuition:'tuition',payment:'payments'};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showToast(m){toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
function initials(e='SH'){return e.split('@')[0].slice(0,2).toUpperCase()}
function role(){return String(currentProfile?.role||'').trim().toLowerCase()}
function isAdmin(){return role()==='admin'}
function money(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat('el-GR',{style:'currency',currency:'EUR'}).format(n):'—'}
function fmtDate(v){if(!v)return '—';try{return new Intl.DateTimeFormat('el-GR').format(new Date(`${v}T12:00:00`))}catch{return v}}
function monthKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function receiptNo(){return `SH-${monthKey().replace('-','')}-${String(Date.now()).slice(-6)}`}
function renderLogin(){root.innerHTML=`<main class="login-shell"><section class="login-hero"><div><span class="hero-badge">School House</span></div><div><h1>School<br>House</h1><p>Μαθητές, απουσίες, δίδακτρα και πληρωμές σε ένα ασφαλές περιβάλλον.</p></div><small>Ασφαλής σύνδεση μέσω Firebase</small></section><section class="login-panel"><div class="login-card"><h2>Καλώς ήρθατε</h2><p>Συνδεθείτε στον λογαριασμό σας.</p><form id="loginForm"><div class="field"><label>Email</label><input id="email" type="email" autocomplete="email" required></div><div class="field"><label>Κωδικός</label><input id="password" type="password" autocomplete="current-password" required></div><button class="primary" type="submit">Σύνδεση</button><div id="loginError" class="error-box"></div></form><div class="login-actions"><span class="muted">Ξεχάσατε τον κωδικό;</span><button id="resetBtn" class="ghost">Επαναφορά</button></div></div></section></main>`;document.getElementById('loginForm').onsubmit=async e=>{e.preventDefault();const box=document.getElementById('loginError');box.style.display='none';try{await signInWithEmailAndPassword(auth,email.value.trim(),password.value)}catch{box.textContent='Δεν ήταν δυνατή η σύνδεση. Ελέγξτε email και κωδικό.';box.style.display='block'}};document.getElementById('resetBtn').onclick=async()=>{const value=email.value.trim();if(!value)return showToast('Γράψτε πρώτα το email σας.');try{await sendPasswordResetEmail(auth,value);showToast('Στάλθηκε email επαναφοράς.')}catch{showToast('Δεν ήταν δυνατή η αποστολή email.')}}}
async function loadProfile(){currentProfile=null;try{const ref=doc(db,'users',currentUser.uid),snap=await getDoc(ref);if(snap.exists()){currentProfile={id:snap.id,...snap.data()};const r=role();if(r&&r!==currentProfile.role){await updateDoc(ref,{role:r});currentProfile.role=r}}firestoreReady=true}catch(e){console.error(e);firestoreReady=false}}
function navButtons(){return NAV.map(([k,l])=>`<button data-view="${k}" class="${currentView===k?'active':''}">${l}</button>`).join('')}
function shell(){const v=views[currentView];root.innerHTML=`<div class="app-shell"><aside class="sidebar"><div class="brand"><div class="mini">SH</div><div><b>School House</b><small>${isAdmin()?'Διαχείριση':'Γονέας'}</small></div></div><nav class="nav">${navButtons()}</nav><div class="sidebar-footer"><small>${esc(currentUser.email)}</small><button class="logout" data-logout>Αποσύνδεση</button></div></aside><main class="main"><header class="topbar"><h2>${v.title}</h2><div class="user-chip"><span class="role-chip">${isAdmin()?'Admin':'Γονέας'}</span><div class="avatar">${initials(currentUser.email)}</div></div></header><div class="content">${v.body()}</div></main><nav class="mobile-nav">${navButtons()}</nav></div>`;bindShell()}
function bindShell(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=()=>signOut(auth));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openEntryModal(b.dataset.add));document.querySelectorAll('[data-student-view]').forEach(b=>b.onclick=()=>openStudentCard(b.dataset.studentView));document.querySelectorAll('[data-student-edit]').forEach(b=>b.onclick=()=>openStudentEdit(b.dataset.studentEdit));document.querySelectorAll('[data-student-delete]').forEach(b=>b.onclick=()=>removeStudent(b.dataset.studentDelete));document.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>printReceipt(lastRows.payments?.find(x=>x.id===b.dataset.receipt)))}
function go(view){currentView=view;shell();view==='dashboard'?loadDashboardStats():loadViewData(view)}
function dashboardHtml(){return `<section class="welcome"><div><h1>School House</h1><p>${isAdmin()?'Η κεντρική εικόνα του φροντιστηρίου σας.':'Η ενημέρωση των μαθητών σας σε ένα σημείο.'}</p></div><span class="pill">Online • Firebase</span></section>${!firestoreReady?'<div class="notice">Δεν ήταν δυνατή η σύνδεση με τη βάση.</div>':''}<div class="stats"><div class="stat"><small>Ενεργοί μαθητές</small><strong id="statStudents">—</strong></div><div class="stat"><small>Απουσίες μήνα</small><strong id="statAbsences">—</strong></div><div class="stat"><small>Εκκρεμή δίδακτρα</small><strong id="statDue">—</strong></div><div class="stat"><small>Πληρωμές μήνα</small><strong id="statPayments">—</strong></div></div><div class="card"><h3>Γρήγορες ενέργειες</h3><div class="quick-actions">${isAdmin()?'<button class="secondary" data-add="student">+ Μαθητής</button><button class="secondary" data-add="absence">+ Απουσία</button><button class="secondary" data-add="tuition">+ Χρέωση</button><button class="secondary" data-add="payment">+ Πληρωμή</button>':''}</div></div>`}
function sectionHead(t,s,a=''){return `<div class="section-title"><div><h1>${t}</h1><p>${s}</p></div>${a}</div>`}
function addButton(type,label){return isAdmin()?`<button class="secondary" data-add="${type}">+ ${label}</button>`:''}
function studentsHtml(){return `${sectionHead('Μαθητές','Καρτέλες μαθητών, κηδεμόνες και οικονομικά στοιχεία.',addButton('student','Νέος μαθητής'))}<div id="studentsData" class="table-wrap"><div class="empty">Φόρτωση μαθητών…</div></div>`}
function absencesHtml(){return `${sectionHead('Απουσίες','Ιστορικό και καταχώρηση απουσιών.',addButton('absence','Καταχώρηση'))}<div id="absencesData" class="table-wrap"><div class="empty">Φόρτωση…</div></div>`}
function tuitionHtml(){return `${sectionHead('Δίδακτρα','Μηνιαίες χρεώσεις και υπόλοιπα.',addButton('tuition','Νέα χρέωση'))}<div id="tuitionData" class="table-wrap"><div class="empty">Φόρτωση…</div></div>`}
function paymentsHtml(){return `${sectionHead('Πληρωμές','Ιστορικό πληρωμών και αποδείξεις.',addButton('payment','Πληρωμή'))}<div id="paymentsData" class="table-wrap"><div class="empty">Φόρτωση…</div></div>`}
function scopedQuery(name,max=200){if(isAdmin()||!currentProfile)return query(collection(db,name),limit(max));return query(collection(db,name),where('parentUid','==',currentUser.uid),limit(max))}
async function getRows(name,max=200){const snap=await getDocs(scopedQuery(name,max));return snap.docs.map(d=>({id:d.id,...d.data()}))}
function table(el,rows,cols,actions=''){if(!rows.length){el.innerHTML='<div class="empty">Δεν υπάρχουν ακόμη καταχωρήσεις.</div>';return}el.innerHTML=`<table class="table"><thead><tr>${cols.map(c=>`<th>${c.label}</th>`).join('')}${actions?'<th>Ενέργειες</th>':''}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c.format?c.format(r[c.key],r):esc(r[c.key]??'—')}</td>`).join('')}${actions?`<td><div class="row-actions">${actions(r)}</div></td>`:''}</tr>`).join('')}</tbody></table>`;bindShell()}
async function loadViewData(view){const map={students:['students','studentsData'],absences:['absences','absencesData'],tuition:['tuition','tuitionData'],payments:['payments','paymentsData']};const [name,target]=map[view]||[];if(!name)return;const el=document.getElementById(target);if(!el)return;try{const rows=await getRows(name);lastRows[name]=rows;firestoreReady=true;if(view==='students')table(el,rows,[{key:'name',label:'Μαθητής'},{key:'className',label:'Τμήμα'},{key:'parentName',label:'Γονέας'},{key:'monthlyFee',label:'Δίδακτρα',format:money},{key:'active',label:'Κατάσταση',format:(v)=>v===false?'<span class="tag red">Ανενεργός</span>':'<span class="tag green">Ενεργός</span>'}],r=>`<button class="tiny" data-student-view="${r.id}">Προβολή</button>${isAdmin()?`<button class="tiny" data-student-edit="${r.id}">Επεξεργασία</button><button class="tiny danger" data-student-delete="${r.id}">Διαγραφή</button>`:''}`);if(view==='absences')table(el,rows,[{key:'studentName',label:'Μαθητής'},{key:'date',label:'Ημερομηνία',format:fmtDate},{key:'lesson',label:'Μάθημα/Τμήμα'},{key:'status',label:'Κατάσταση'}]);if(view==='tuition')table(el,rows,[{key:'studentName',label:'Μαθητής'},{key:'month',label:'Μήνας'},{key:'amount',label:'Ποσό',format:money},{key:'status',label:'Κατάσταση'}]);if(view==='payments')table(el,rows,[{key:'studentName',label:'Μαθητής'},{key:'date',label:'Ημερομηνία',format:fmtDate},{key:'month',label:'Περίοδος'},{key:'amount',label:'Ποσό',format:money},{key:'receiptNo',label:'Απόδειξη'}],r=>`<button class="tiny" data-receipt="${r.id}">Απόδειξη</button>`)}catch(e){console.error(e);firestoreReady=false;el.innerHTML=`<div class="notice">Δεν ήταν δυνατή η φόρτωση (${esc(e?.code||'σφάλμα')}).</div>`}}
async function loadDashboardStats(){try{const [s,a,t,p]=await Promise.all(['students','absences','tuition','payments'].map(n=>getRows(n)));lastRows={...lastRows,students:s,absences:a,tuition:t,payments:p};const due=t.filter(x=>!['paid','εξοφλημένο'].includes(String(x.status||'').toLowerCase())).reduce((n,x)=>n+Number(x.amount||0),0),pm=p.filter(x=>String(x.date||'').startsWith(monthKey())).reduce((n,x)=>n+Number(x.amount||0),0);document.getElementById('statStudents').textContent=s.filter(x=>x.active!==false).length;document.getElementById('statAbsences').textContent=a.filter(x=>String(x.date||'').startsWith(monthKey())).length;document.getElementById('statDue').textContent=money(due);document.getElementById('statPayments').textContent=money(pm);firestoreReady=true}catch(e){console.error(e);firestoreReady=false}}
async function studentsForSelect(){const rows=lastRows.students?.length?lastRows.students:await getRows('students');lastRows.students=rows;return rows.filter(x=>x.active!==false)}
function fieldHtml(f,value=''){const [n,l,t,r]=f;if(t==='select')return `<div class="field"><label>${l}</label><select name="${n}" ${r?'required':''}>${value}</select></div>`;return `<div class="field"><label>${l}</label><input name="${n}" type="${t}" ${r?'required':''} value="${esc(value)}"></div>`}
const templates={student:{title:'Νέος μαθητής',fields:[['name','Ονοματεπώνυμο','text',true],['className','Τμήμα','text',true],['parentName','Ονοματεπώνυμο γονέα','text',true],['parentEmail','Email γονέα','email',true],['monthlyFee','Μηνιαία δίδακτρα (€)','number',true],['notes','Σημειώσεις','text',false]]},absence:{title:'Νέα απουσία',fields:[['studentId','Μαθητής','select',true],['date','Ημερομηνία','date',true],['lesson','Μάθημα/Τμήμα','text',true],['status','Κατάσταση','text',true]]},tuition:{title:'Νέα χρέωση',fields:[['studentId','Μαθητής','select',true],['month','Μήνας','month',true],['amount','Ποσό (€)','number',true],['status','Κατάσταση','text',true]]},payment:{title:'Νέα πληρωμή',fields:[['studentId','Μαθητής','select',true],['date','Ημερομηνία','date',true],['month','Μήνας που αφορά','month',true],['amount','Ποσό (€)','number',true],['method','Τρόπος πληρωμής','text',true]]}};
async function openEntryModal(type){if(!isAdmin())return showToast('Η ενέργεια επιτρέπεται μόνο στον διαχειριστή.');const cfg=templates[type],students=type==='student'?[]:await studentsForSelect();if(type!=='student'&&!students.length)return showToast('Δημιουργήστε πρώτα έναν ενεργό μαθητή.');const wrap=document.createElement('div');wrap.className='modal-backdrop';const options=students.map(s=>`<option value="${s.id}">${esc(s.name)}${s.className?` — ${esc(s.className)}`:''}</option>`).join('');wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>${cfg.title}</h3><button class="modal-x" type="button">×</button></div><form id="entryForm">${cfg.fields.map(f=>fieldHtml(f,f[2]==='select'?options:(f[0]==='date'?new Date().toISOString().slice(0,10):f[0]==='month'?monthKey():''))).join('')}<button class="primary" type="submit">Αποθήκευση</button></form></div>`;document.body.appendChild(wrap);bindModalClose(wrap);wrap.querySelector('form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));try{if(data.studentId){const s=students.find(x=>x.id===data.studentId);data.studentName=s?.name||'';if(s?.parentUid)data.parentUid=s.parentUid}await saveEntry(type,data);wrap.remove();showToast('Η καταχώρηση αποθηκεύτηκε.');go(currentView)}catch(err){console.error(err);showToast(`Αποτυχία αποθήκευσης (${err?.code||'σφάλμα'}).`)}}}
function bindModalClose(w){w.querySelector('.modal-x').onclick=()=>w.remove();w.onclick=e=>{if(e.target===w)w.remove()}}
async function saveEntry(type,data){const payload={...data,createdAt:serverTimestamp(),createdBy:currentUser.uid};if('amount'in payload)payload.amount=Number(payload.amount);if('monthlyFee'in payload)payload.monthlyFee=Number(payload.monthlyFee);if(type==='student')payload.active=true;if(type==='payment')payload.receiptNo=receiptNo();await addDoc(collection(db,COLLECTIONS[type]),payload)}
function findStudent(id){return lastRows.students?.find(x=>x.id===id)}
async function openStudentCard(id){let s=findStudent(id);if(!s){const snap=await getDoc(doc(db,'students',id));if(!snap.exists())return;s={id:snap.id,...snap.data()}}const wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>${esc(s.name)}</h3><button class="modal-x">×</button></div><div class="detail-grid"><div><small>Τμήμα</small><b>${esc(s.className||'—')}</b></div><div><small>Κατάσταση</small><b>${s.active===false?'Ανενεργός':'Ενεργός'}</b></div><div><small>Γονέας</small><b>${esc(s.parentName||'—')}</b></div><div><small>Email</small><b>${esc(s.parentEmail||'—')}</b></div><div><small>Μηνιαία δίδακτρα</small><b>${money(s.monthlyFee)}</b></div><div class="wide"><small>Σημειώσεις</small><b>${esc(s.notes||'—')}</b></div></div>${isAdmin()?`<div class="modal-actions"><button class="secondary" data-edit-now>Επεξεργασία</button></div>`:''}</div>`;document.body.appendChild(wrap);bindModalClose(wrap);wrap.querySelector('[data-edit-now]')?.addEventListener('click',()=>{wrap.remove();openStudentEdit(id)})}
async function openStudentEdit(id){if(!isAdmin())return;const s=findStudent(id);if(!s)return showToast('Δεν βρέθηκε ο μαθητής.');const fields=templates.student.fields,wrap=document.createElement('div');wrap.className='modal-backdrop';wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>Επεξεργασία μαθητή</h3><button class="modal-x">×</button></div><form>${fields.map(f=>fieldHtml(f,s[f[0]]??'')).join('')}<div class="field"><label>Κατάσταση</label><select name="active"><option value="true" ${s.active!==false?'selected':''}>Ενεργός</option><option value="false" ${s.active===false?'selected':''}>Ανενεργός</option></select></div><button class="primary">Αποθήκευση αλλαγών</button></form></div>`;document.body.appendChild(wrap);bindModalClose(wrap);wrap.querySelector('form').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.monthlyFee=Number(data.monthlyFee);data.active=data.active==='true';data.updatedAt=serverTimestamp();data.updatedBy=currentUser.uid;try{await updateDoc(doc(db,'students',id),data);wrap.remove();showToast('Οι αλλαγές αποθηκεύτηκαν.');go('students')}catch(err){console.error(err);showToast('Δεν ήταν δυνατή η ενημέρωση.')}}}
async function removeStudent(id){if(!isAdmin())return;const s=findStudent(id);if(!s)return;if(!confirm(`Να διαγραφεί ο μαθητής «${s.name}»; Οι υπάρχουσες οικονομικές/απουσιολογικές εγγραφές δεν θα διαγραφούν.`))return;try{await deleteDoc(doc(db,'students',id));showToast('Ο μαθητής διαγράφηκε.');go('students')}catch(e){console.error(e);showToast('Δεν ήταν δυνατή η διαγραφή.')}}
function printReceipt(p){if(!p)return showToast('Δεν βρέθηκε η πληρωμή.');const html=`<!doctype html><html lang="el"><head><meta charset="utf-8"><title>${esc(p.receiptNo||'Απόδειξη')}</title><style>body{font-family:system-ui;padding:40px;max-width:620px;margin:auto}h1{color:#16324f}.box{border:1px solid #ddd;border-radius:16px;padding:20px}button{padding:10px 14px}</style></head><body><h1>School House</h1><div class="box"><h2>Απόδειξη πληρωμής</h2><p><b>Αριθμός:</b> ${esc(p.receiptNo||'—')}</p><p><b>Μαθητής:</b> ${esc(p.studentName||'—')}</p><p><b>Ημερομηνία:</b> ${esc(fmtDate(p.date))}</p><p><b>Περίοδος:</b> ${esc(p.month||'—')}</p><p><b>Ποσό:</b> ${money(p.amount)}</p><p><b>Τρόπος:</b> ${esc(p.method||'—')}</p></div><p><button onclick="window.print()">Εκτύπωση / PDF</button></p></body></html>`;const w=window.open('','_blank');if(!w)return showToast('Επιτρέψτε το άνοιγμα παραθύρου για την απόδειξη.');w.document.write(html);w.document.close();setTimeout(()=>w.print(),250)}
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){renderLogin();return}await loadProfile();currentView='dashboard';shell();loadDashboardStats()});
